export const OPPORTUNITY_STATES = [
  "HIGH_CONFIDENCE_FLIP",
  "GRADE_CANDIDATE",
  "INSPECT_PHOTOS",
  "WATCH",
  "PASS",
  "REJECTED_CARD_IDENTITY_UNCERTAIN",
  "REJECTED_MARGIN_TOO_LOW",
  "REJECTED_LIQUIDITY_TOO_LOW",
] as const;

export type OpportunityState = (typeof OPPORTUNITY_STATES)[number];

export const STATE_LABELS: Record<OpportunityState, string> = {
  HIGH_CONFIDENCE_FLIP: "HIGH CONFIDENCE FLIP",
  GRADE_CANDIDATE: "GRADE CANDIDATE",
  INSPECT_PHOTOS: "INSPECT PHOTOS",
  WATCH: "WATCH",
  PASS: "PASS",
  REJECTED_CARD_IDENTITY_UNCERTAIN: "REJECTED — CARD IDENTITY UNCERTAIN",
  REJECTED_MARGIN_TOO_LOW: "REJECTED — MARGIN TOO LOW",
  REJECTED_LIQUIDITY_TOO_LOW: "REJECTED — LIQUIDITY TOO LOW",
};
